Finished spec
MimiLevy/IDF-Business-Scenario pull request #2
Opened 2021-12-22 21:49 UTC by shmielminz

Hope I understood it well.

2021-12-29 19:27 UTC, MimiLevy commented on ArmedForcesDB/0 Database.sql
> +use master
wrong

2021-12-30 11:51 UTC, MimiLevy commented on ArmedForcesDB/1 table.sql
> +use ArmedForcesDB
--ML: nice job! 100%
Please see comments below.

2021-12-30 12:10 UTC, MimiLevy commented on ArmedForcesDB/1 table.sql
> +    SSN varchar(10) not null constraint ck_ArmedForces_ssn_must_be_9_or_10_digits_and_must_be_numeric check(SSN like replicate('[0-9]',9) or SSN like replicate('[0-9]',10)),
The SSN should be inserted into the system in this structure: 8 numbers in a row and a dash before the check digit (the first digit on the right).

2021-12-30 12:31 UTC, MimiLevy commented on ArmedForcesDB/1 table.sql
> +)
--ML: No need to specify Date Of Birth since in Israel the ID numbers are unique.

2021-12-30 12:34 UTC, MimiLevy commented
Very nice job! 99%
Please see comments and resubmit.

2021-12-30 12:48 UTC, MimiLevy requested changes
Very nice job! 99%
Please see comments and resubmit.

2022-01-02 10:46 UTC, MimiLevy reviewed
Great Job! 100%

2022-01-02 10:49 UTC, MimiLevy commented
Great Job! 100%

2022-01-03 14:15 UTC, LeahBineth approved these changes

2025-09-30 16:51 UTC, closed without merging